#!/usr/bin/env python3
"""Build the OSI licence catalogue consumed by the LC### and LD### rules.

Two inputs, two very different trust levels:

* **SPDX** (`spdx/license-list-data`, `json/licenses.json`) is machine
  readable and authoritative for *facts* — the identifier, the display
  name, whether the OSI approved it, and whether SPDX has deprecated the
  identifier. This half refreshes automatically.
* **The overlay** (`sync-files/legal/osi-overlay.json`) is hand-curated
  *judgement* — the OSI category (popular / superseded / retired / ...),
  the replacement identifier to recommend, the reasons a source-available
  licence is not open source, and the handful of identifiers the OSI
  lists but SPDX's `isOsiApproved` does not reflect. None of this exists
  in SPDX, and it cannot be derived from `isDeprecatedLicenseId`:
  `EPL-1.0` is not SPDX-deprecated but is OSI-superseded, while `GPL-2.0`
  and `AGPL-3.0` are SPDX-deprecated yet sit in OSI's "Popular / Strong
  Community" category.

The merge is deliberately strict. An overlay entry naming an identifier
the OSI no longer approves, or a `prefer` target that is not itself
approved, fails the build rather than silently dropping — a stale
recommendation in a policy dataset is worse than a red pipeline.

Usage:
    build_osi_catalogue.py --spdx json/licenses.json [--check]
    build_osi_catalogue.py --derive-overlay          # bootstrap the overlay
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path
from typing import Any

HUB_ROOT = Path(__file__).resolve().parents[1]
LEGAL_DIR = HUB_ROOT / "sync-files" / "legal"
OVERLAY_PATH = LEGAL_DIR / "osi-overlay.json"
CATALOGUE_PATH = LEGAL_DIR / "osi-licenses.json"

OSI_URL = "https://opensource.org/licenses"

_COMMENT = [
    "Generated by scripts/build_osi_catalogue.py — do not edit by hand.",
    "Facts (identifier, name, OSI approval, SPDX deprecation) come from the",
    "SPDX license list; judgement (category, prefer, not_open_source) comes",
    "from sync-files/legal/osi-overlay.json, which is curated against",
    "https://opensource.org/licenses because the OSI publishes its category",
    "filters only as HTML. Fanned out to the kits by managed file sync.",
]

# Categories the overlay is allowed to assign, mirroring the OSI filters.
CATEGORIES = frozenset({
    "popular", "superseded", "retired", "non-reusable", "redundant",
    "international", "special-purpose", "legacy", "other", "uncategorized",
})

# How strongly a licence propagates its own terms to a combined work.
# Drives the inbound-compatibility verdicts; `unknown` means the engine
# declines to rule rather than guessing.
RECIPROCITY = frozenset({
    "public-domain", "permissive", "weak-copyleft",
    "strong-copyleft", "network-copyleft", "unknown",
})


def _load(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        sys.exit(f"error: {path} not found")
    except json.JSONDecodeError as exc:
        sys.exit(f"error: {path}: invalid JSON: {exc}")


def _dump(document: dict[str, Any], path: Path) -> str:
    """Serialise deterministically so an unchanged upstream yields no diff."""
    return json.dumps(document, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def build(spdx_path: Path) -> tuple[dict[str, Any], list[str]]:
    """Merge SPDX facts with the curated overlay. Returns (catalogue, notes)."""
    spdx = _load(spdx_path)
    overlay = _load(OVERLAY_PATH)
    entries = spdx.get("licenses")
    if not isinstance(entries, list):
        sys.exit(f"error: {spdx_path}: expected a top-level `licenses` array")

    approved: dict[str, dict[str, Any]] = {}
    spdx_by_id: dict[str, dict[str, Any]] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        identifier = str(entry.get("licenseId") or "").strip()
        if not identifier:
            continue
        spdx_by_id[identifier] = entry
        if entry.get("isOsiApproved"):
            approved[identifier] = {
                "name": str(entry.get("name") or identifier).strip(),
                "deprecated": bool(entry.get("isDeprecatedLicenseId")),
                "osi_only": False,
            }

    if not approved:
        sys.exit(f"error: {spdx_path}: no OSI-approved licences found")

    overlay_licenses = overlay.get("licenses") or {}
    not_open_source = overlay.get("not_open_source") or {}
    osi_only = overlay.get("osi_approved_not_in_spdx") or {}
    errors: list[str] = []
    notes: list[str] = []

    # The OSI's own list is the authority on OSI approval; SPDX's
    # `isOsiApproved` mirrors it imperfectly (it reports false for
    # `curl`, `MIT-CMU`, `GPL-1.0`, and `eCos-2.0`, all of which the OSI
    # publishes). The overlay may reinstate those, but only with a reason
    # and only when SPDX still carries the identifier for its name.
    for identifier, reason in sorted(osi_only.items()):
        if identifier in approved:
            notes.append(
                f"{identifier} is now OSI-approved upstream — drop it from "
                "`osi_approved_not_in_spdx`")
            continue
        entry = spdx_by_id.get(identifier)
        if entry is None:
            errors.append(
                f"`{identifier}` is in `osi_approved_not_in_spdx` but SPDX does "
                "not carry the identifier at all")
            continue
        if not str(reason).strip():
            errors.append(f"`{identifier}` needs a reason in `osi_approved_not_in_spdx`")
        approved[identifier] = {
            "name": str(entry.get("name") or identifier).strip(),
            "deprecated": bool(entry.get("isDeprecatedLicenseId")),
            "osi_only": True,
        }

    # An overlay entry for something the OSI no longer approves means the
    # curated judgement has drifted from upstream. Never silently drop it.
    for identifier in sorted(overlay_licenses):
        if identifier not in approved:
            errors.append(
                f"overlay names `{identifier}`, which is not OSI-approved in "
                f"{spdx_path.name} — remove it from the overlay, or move it to "
                "`not_open_source` if the OSI retired the approval")

    for identifier, reason in sorted(not_open_source.items()):
        if identifier in approved:
            errors.append(
                f"`{identifier}` is listed as not open source but SPDX reports "
                "it as OSI-approved — the overlay contradicts upstream")
        if not str(reason).strip():
            errors.append(f"`{identifier}` has an empty not_open_source reason")

    licenses: dict[str, Any] = {}
    for identifier in sorted(approved, key=str.lower):
        facts = approved[identifier]
        curated = overlay_licenses.get(identifier) or {}
        category = curated.get("category", "uncategorized")
        if category not in CATEGORIES:
            errors.append(f"`{identifier}` has unknown category `{category}`")
        reciprocity_class = curated.get("reciprocity", "unknown")
        if reciprocity_class not in RECIPROCITY:
            errors.append(
                f"`{identifier}` has unknown reciprocity `{reciprocity_class}`")
        if identifier not in overlay_licenses:
            notes.append(f"{identifier} is newly OSI-approved and needs a category")
        licenses[identifier] = {
            "name": facts["name"],
            "category": category,
            "reciprocity": reciprocity_class,
            "prefer": curated.get("prefer"),
            "deprecated": facts["deprecated"],
            "osi_only": facts["osi_only"],
        }

    for identifier, body in licenses.items():
        prefer = body["prefer"]
        if prefer is not None and prefer not in licenses:
            errors.append(
                f"`{identifier}` prefers `{prefer}`, which is not an "
                "OSI-approved identifier")
        if body["category"] in ("superseded", "retired") and not prefer:
            notes.append(f"{identifier} is {body['category']} with no replacement named")

    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        sys.exit(1)

    catalogue = {
        "_comment": _COMMENT,
        "source": OSI_URL,
        "spdx_source": "https://github.com/spdx/license-list-data",
        "spdx_license_list_version": str(spdx.get("licenseListVersion") or "unknown"),
        "snapshot": dt.date.today().isoformat(),
        "licenses": licenses,
        "not_open_source": dict(sorted(not_open_source.items(), key=lambda kv: kv[0].lower())),
    }
    return catalogue, notes

def derive_overlay() -> int:
    """Bootstrap the overlay from an existing hand-written catalogue."""
    existing = _load(CATALOGUE_PATH)
    overlay = {
        "_comment": [
            "Hand-curated judgement that SPDX does not publish: the OSI",
            "category, the replacement to recommend for a superseded or",
            "retired licence, and why a source-available licence is not open",
            "source. Curated against https://opensource.org/licenses, whose",
            "category filters exist only as HTML. Merged with SPDX facts by",
            "scripts/build_osi_catalogue.py.",
        ],
        "licenses": {
            identifier: {
                "category": body.get("category", "uncategorized"),
                "reciprocity": body.get("reciprocity", "unknown"),
                "prefer": body.get("prefer"),
            }
            for identifier, body in sorted(
                (existing.get("licenses") or {}).items(), key=lambda kv: kv[0].lower())
        },
        "not_open_source": dict(sorted(
            (existing.get("not_open_source") or {}).items(),
            key=lambda kv: kv[0].lower())),
    }
    OVERLAY_PATH.write_text(_dump(overlay, OVERLAY_PATH), encoding="utf-8")
    print(f"wrote {OVERLAY_PATH} ({len(overlay['licenses'])} curated entries)")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spdx", type=Path,
                        help="path to the SPDX json/licenses.json")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when the catalogue on disk is out of date")
    parser.add_argument("--derive-overlay", action="store_true",
                        help="regenerate the overlay from the current catalogue")
    args = parser.parse_args(argv)

    if args.derive_overlay:
        return derive_overlay()
    if not args.spdx:
        parser.error("--spdx is required unless --derive-overlay is given")

    catalogue, notes = build(args.spdx)
    rendered = _dump(catalogue, CATALOGUE_PATH)

    if args.check:
        current = CATALOGUE_PATH.read_text(encoding="utf-8") if CATALOGUE_PATH.is_file() else ""
        # `snapshot` moves with the clock, so compare everything else.
        if _payload(current) == _payload(rendered):
            print("osi-licenses.json is up to date")
            return 0
        print("osi-licenses.json is out of date — run without --check", file=sys.stderr)
        return 1

    CATALOGUE_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {CATALOGUE_PATH} "
          f"({len(catalogue['licenses'])} OSI-approved, "
          f"{len(catalogue['not_open_source'])} not open source, "
          f"SPDX {catalogue['spdx_license_list_version']})")
    for note in notes:
        print(f"::warning::osi-catalogue: {note}")
    return 0


def _payload(text: str) -> str:
    """Strip the volatile `snapshot` date so `--check` only sees real drift."""
    if not text.strip():
        return ""
    try:
        doc = json.loads(text)
    except json.JSONDecodeError:
        return text
    doc.pop("snapshot", None)
    return json.dumps(doc, indent=2, ensure_ascii=False, sort_keys=False)


if __name__ == "__main__":
    raise SystemExit(main())
